### ISSUE TITLE
imagemin-pngquant not loading correctly

### ISSUE THREAD

**Issue by jonnyserra** [jackfranklin/gulp-load-plugins#111]
So i'm having some problems with any package that's not prefixed by the word "gulp" for instance if i try to use imagemin-pngquant i'm screwed since this package defaults to only loading files prefixed with the word gulp... 

Why is this the case? why not default to loading everything in package.json and then allow people to be more specific if they wish?

**Comment by shinnn** [comment]
Duplicate of https://github.com/jackfranklin/gulp-load-plugins/issues/84 https://github.com/jackfranklin/gulp-load-plugins/issues/83

**Comment by jonnyserra** [comment]
I'd already figured that out from the documentation, but **why** is it like that? It doesn't make much sense to me, why would you add a default rule that restricts your app's usage? A lot of people use more than just gulp modules, and several gulp modules have **their own** modules, imagemin being a great example, it just doesn't make sense to me.

**Comment by callumacrae** [comment]
Because this is a project for loading gulp plugins, and per the gulp plugin guidelines, gulp plugins should begin with `gulp-`. There are very few libraries that work out of the box as gulp plugins.

You might be interested in this issue and the linked projects: https://github.com/jackfranklin/gulp-load-plugins/issues/77

**Comment by jackfranklin** [comment]
@jonnyserra a lot of people use this plugin to load all their npm packages, which is fine, but this project has always been specifically focused on Gulp plugins (the clue is in the name) - you can configure it to load everything and there are also other modules that do that if you'd rather use one of them.

The goal with scoping the loading to `gulp-*` and `gulp.*` by default was to ensure the plugin is never over eager in what it loads - but the point of exposing all the configuration is so that you can configure it how you'd like.
