### ISSUE TITLE
Rename & ReplaceString

### ISSUE THREAD

**Issue by TuckerWhitehouse** [jackfranklin/gulp-load-plugins#53]
Would be convenient if the ```replaceString``` was prepended to a ```rename``` key if it doesn't match the ```pattern```. For example, ```6to5``` does not match ```gulp-*```, so prepended it with ```gulp-```.
```js
var plugins = require('gulp-load-plugins')({
  rename: { '6to5': 'to5' }
})
```

**Comment by jackfranklin** [comment]
I'm a little against this purely because I'd rather be explicit. Correct me if I'm wrong, but you'd like the above to effectively work equivalentlu to:

```js
var plugins = require('gulp-load-plugins')({
  rename: { 'gulp-6to5': 'to5' }
})
```

This gets complex when the user has changed the replaceString or they have added an array of replacements, because which one do you use then? Indeed, the default replace string in the plugin is actually `['gulp-*', 'gulp.*']` (the docs need to be updated), so I'm not sure this would work reliably without being more harm than good.
