### ISSUE TITLE
Problem with `config` option on Windows.

### ISSUE THREAD

**Issue by vkbansal** [jackfranklin/gulp-load-plugins#76]
Plugins does not work on Windows with
```js
{
    config: "package.json"
}
```

Instead must use the following
```js
{
    config: path.join(__dirname, "package.json")
}
```

**Comment by callumacrae** [comment]
Why would you want to set `config` to package.json? That's the default!

Does it work with other paths like `../package.json` and `foo/package.json`? Just trying to work out where the problem is—I think it's with the `path.dirname()` call [here](https://github.com/jackfranklin/gulp-load-plugins/blob/master/index.js#L38).

**Comment by fergaldoyle** [comment]
`../package.json`  does not work. I'd like to use a `package.json` in the parent directory but it's not working.

**Comment by jackfranklin** [comment]
Did we ever get anywhere with this? I'm wondering if `config: path.join(__dirname, './package.json')` works more reliably across OS's then maybe we should make that the default?

**Comment by jackfranklin** [comment]
Closing - if anyone else finds this issue please let me know.
