### ISSUE TITLE
camelize should just control camelcase

### ISSUE THREAD

**Issue by tcurdt** [jackfranklin/gulp-load-plugins#82]
With `camelize: true` the name `gulp-front-matter` gets turned into `frontMatter`.
With `camelize: false` the name `gulp-front-matter` gets turned into `front-matter`.

So not only does the option control the camel case but also the stripping of the hyphen.
I think this should be split this into two options. Something along the lines of this https://repl.it/zZu/1 :

    var fnCamel = function(s) {
        return s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();
    }

    var fnStrip = function(s, camel) {
        return s.split('-').map(function(w, i){
            return (i !== 0 && camel) ? fnCamel(w) : w;
        }).join('')
    }

    var fnTransform = function(example, strip, camel) {
        if (strip) {
            return fnStrip(example, camel);
        } else {
            return example;
        }
    };

    var examples = [ "front-matter-thing", "front-matTer" ];
    var camels = [ true, false ];
    var strips = [ true, false ];

    examples.forEach(function(example){
      strips.forEach(function(strip){
        camels.forEach(function(camel){
          console.log("strip:", strip, "camel:", camel);
          console.log(" ", example, " -> ", fnTransform(example, strip, camel));
        });
      });
    });

**Comment by callumacrae** [comment]
Camelize is converting a hyphenated string into a camel case string. What's counter-intuitive about that? would advantage would an option bring?

**Comment by tcurdt** [comment]
@callumacrae Well, I guess it depends of the definition of 'camelize' - to me the current behaviour is strip and camelize. Camelcase is applied to collection of words - the fact that they are connected by a hyphen is another matter.

Right now 'camelize' being `false` doesn't provide much value - at least I'd be missing it.

Frankly speaking - it might just be better to expose the mapping function as parameter (than adding yet another specific `strip` option). It would just implement camelize by default (as is) and one could get rid of the `rename` and `camelize` options.

Given that that would be a breaking change I fear it's probably no option though.

**Comment by jackfranklin** [comment]
I think I agree with @callumacrae on this one. To me given the string `gulp-front-matter`, camelizing it is the process of stripping hyphens and then camel casing the string. What would happen if we did introduce a second option for stripping hyphens, and then you gave it the string `gulp-front-matter` with `camelize: true`, strip: false`, or something?

I don't like the idea of adding `strip` because as you say it's another pretty specific option and this plugin already has enough of them, polus I'm not convinced it makes sense, given what I said above.

I do quite like the idea of having a mapping function to allow people to control this very specifically if they want to, but that's kind of why the `rename` functionality exists, for these situations where you're not happy with how the plugin is renaming something and just want to explicitly tell it what to do. However, most people find `camelize: true` to be exactly what they need (if I could, I'd probably remove the option to turn it off tbh).

> Camelcase is applied to collection of words - the fact that they are connected by a hyphen is another matter.

Not in the context of this plugin though, camelize is always something applied to the name of a gulp plugin.

**Comment by tcurdt** [comment]
@jackfranklin I can see that `camelize: true` being the default and enough most of the time. Especially as I think `camelize: false` does not make any sense (otherwise you have to use e.g. plugins['front-matter']).

So as I said - I would give up the `camelize` and improve on the mapping. Instead of the literal 'rename' mapping the plugin could also support a mapping function. That would mean full flexibility and dropping of one option. All it needs is a check of the `rename` option whether it's a function or not.

**Comment by tcurdt** [comment]
So for the future I would deprecate the `camelize` option and add the support for the rename function.

**Comment by callumacrae** [comment]
Or have the default rename function use the camlize option to avoid breaking BC

**Comment by tcurdt** [comment]
@callumacrae sure - that would be for the deprecation period where there could be a warning on the console if it's being used.

**Comment by callumacrae** [comment]
I will gladly tackle this one when I'm capable :)

**Comment by jackfranklin** [comment]
:+1: sounds like a good ground. @tcurdt please feel free to have a crack at an implementation, more than happy to help with it.

@callumacrae concentrate on getting better! ;)
