### ISSUE TITLE
Time impact running this plugin

### ISSUE THREAD

**Issue by Martinspire** [jackfranklin/gulp-load-plugins#92]
Since this plugin will need to find out what plugins are required, it seems to me this will take up some time. The readme however doesn't state this nor how much it will be. Shouldn't this at least be mentioned? The time it takes seems like a dealbreaker to me for me using this plugin.
And whats also not clear from the readme is if this is a one-time thing for starting Gulp or one that will keep loading the proper plugins when you watch some files.

**Comment by jackfranklin** [comment]
Finding out what plugins are running is a case of reading in a local JSON file and parsing it - I have not profiled it but I doubt this would have much of an impact if any at all. This would be fairly easy to profile if you had two Gulp files, one that used this plugin and one that didn't.

Additionally the plugin lazy loads by default, so say you're loading 10 plugins but the task you want to run only uses 2 of them, you should see a huge speed boost because only those 2 plugins actually get `require`d. (The boost gets bigger the more plugins you have). gulp-load-plugins will only ever require each plugin once.

I hope that answers your question but LMK if it doesn't :)
